project_name: garble

builds:
  - main: .
    id: "garble"
    binary: garble
    env: [CGO_ENABLED=0]
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm64
    goarm:
      - 6
      - 7

archives:
  - 
    id: "garble"
    builds: ['garble']
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    format: binary

release:
  github:
  disable: false

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256
