name: Release

on:
  push:
    tags:
      - "v*.*.*"
    branches: master

jobs:
  build:
    name: Release Build
    if: startsWith( github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.2"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Mkdir Bin
        run: mkdir ./bin

      - name: Compile Linux
        run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o ./bin/garble_linux .

      - name: Compile Linux
        run: GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -o ./bin/garble_linux-arm64 .

      - name: Compile Windows
        run: GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -o ./bin/garble_windows.exe .

      - name: Make AMD64
        run: GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -o ./bin/garble_macos-amd64 .

      - name: Make ARM64
        run: GOOS=darwin GOARCH=arm64 CGO_ENABLED=0 go build -o ./bin/garble_macos-arm64 .

      - name: "Publish Release"
        uses: "bishopfox/action-gh-release@v1"
        with:
          files: |
            ./bin/*
